title: Deep Learning Portfolio
author: Joanna Reyda D. Santos
copyright: "2025"
logo: logo.png

execute:
  execute_notebooks: force

html:
  favicon: logo.png
  static_path:
    - _static
  css_files:
    - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    - custom.css

  footer_items:
    - text: "Copyright © 2025, Joanna Reyda D. Santos"
  extra_footer: |
    <p>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>.</p>

repository:
  url: https://github.com/LadyJo02/deep-learning-portfolio
  branch: main
  use_repository_button: true

sphinx:
  config:
    html_theme_options:
      use_light_mode_button: true